(defvar tablesize 9)
(defvar table (generateTable tablesize))
(defvar played-move '())
(defvar valuemoja 5)
(defvar newtable '())
(defvar player)
(defvar end-time 25)
(defvar best-move)
;;(defvar player1 (if (equal player 'x) 'o 'x))
;;;defvar graph-of-states (add-to-graph '() table (car (gen-all-possible-states 'x '1 '1 table))))